version: "3"
services:  
  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "32700:5432"
    restart: always